name: ubuntu-actions
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Verbose ubuntu script
        run: |
          chmod +x startup.sh
          VERBOSE=1 ./startup.sh

